-- Add NFT-related fields to Clip table
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "royaltyBps" INTEGER;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "metadataUri" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "mintAddress" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "mintedAt" TIMESTAMP(3);
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "nftStatus" TEXT NOT NULL DEFAULT 'none';
